name: Cache Node and NPM Dependencies
description: This action caches both Node and NPM dependencies based on the package-lock.json file.

inputs:
  node-version:
    description: NodeJS version to use
    default: 20.x
    required: false
  working-dir:
    description: The working directory of the application
    default: "."
    required: false
  # cache-key:

runs:
  using: composite
  steps:
    - name: Setup NodeJS version ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.working-dir }}/node_modules
        key: node-modules-${{ hashFiles(format('{0}/package-lock.json', inputs.working-dir))}}

    - name: Install dependencies
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      working-directory: ${{ inputs.working-dir }}
      shell: bash
      run: npm ci
