name: 12 - Working with Outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        description: Build status
        options:
          - success
          - failure
        default: success

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.STATUS }}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo "$GITHUB_OUTPUT"
      - name: Build
        id: build
        run: |
          echo "$GITHUB_OUTPUT"
          echo "STATUS=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"
          echo "FOO=foo" >> "$GITHUB_OUTPUT"
          echo "BAR=bar" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"
      - name: Overwrite contents of GITHUB_OUTPUT
        run: |
          echo "$GITHUB_OUTPUT"
          echo "BAZ=baz" >> "$GITHUB_OUTPUT"
          echo "BAZ1=baz1" > "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.build-status == 'success' }}
    steps:
      - name: Deploy
        run: echo "Deploying"
