name: 13 - Use Caching

on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: Execute cache step
        type: boolean
        default: true
      node-version:
        description: Node version
        type: choice
        options:
          - 18.x
          - 20.x
          - latest
        default: 20.x

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 13-caching/react-app
    outputs:
      deps-cache-key: ${{ steps.cache-key.outputs.cache.CACHE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Calculate cache key
        id: cache-key
        run: |
          echo "CACHE_KEY=deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}" >> "$GITHUB_OUTPUT"

      - name: Download cached dependencies
        uses: actions/cache@v4
        if: ${{ inputs.use-cache }}
        id: cache
        with:
          path: 13-caching/react-app/node_modules
          key: ${{ steps.cache-key.outputs.CACHE_KEY }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

  lint-test:
    runs-on: ubuntu-latest
    needs: install-dependencies
    defaults:
      run:
        working-directory: 13-caching/react-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Download cached dependencies
        uses: actions/cache@v4
        if: ${{ inputs.use-cache }}
        id: cache
        with:
          path: 13-caching/react-app/node_modules
          key: ${{ needs.install-dependencies.outputs.deps-cache-key }}

      - name: Testing
        run: npm run test

      - name: Linting
        run: echo "Linting..."

  build:
    runs-on: ubuntu-latest
    needs: install-dependencies
    defaults:
      run:
        working-directory: 13-caching/react-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Download cached dependencies
        uses: actions/cache@v4
        if: ${{ inputs.use-cache }}
        id: cache
        with:
          path: 13-caching/react-app/node_modules
          key: ${{ needs.install-dependencies.outputs.deps-cache-key }}

      - name: Building
        run: npm run build

      # - name: Deploy to non-prod
      #   run: echo 'Deploying to non-prod'
