name: 13 - Use Caching

on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: Execute cache step
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 13-caching/react-app

    # Checkout code
    # Install dependencies
    # Linting, formatting, unit testing, building
    # Deploy to non-prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: npm ci

      - name: Testing
        run: npm run test

      - name: Building
        run: npm run build

      - name: Deploy to non-prod
        run: echo 'Deploying to non-prod'
