name: 15 - Working with Matrices

on: workflow_dispatch

jobs:
  backwards-compatibility:
    name: ${{ matrix.os }}-${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 21.x]
        os:
          - ubuntu-latest
          # - macos-latest
          - windows-latest
        include:
          - os: ubuntu-latest
            node-version: 16.x

    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Perform some test
        run: |
          echo "Running tests on OS: ${{matrix.os}} and NodeJS ${{ matrix.node-version }}"
