name: 17-2 - Custom Actions JS
run-name: 17-2 - Custom Actions JS | BB - ${{ inputs.base-branch }} | TB - ${{ inputs .head-branch }} | WD - ${{ inputs.working-directory }}

on:
  workflow_dispatch:
    inputs:
      base-branch:
        type: string
        default: main
      head-branch:
        type: string
        default: update-dependencies
      working-directory:
        type: string
        default: 17-custom-actions/react-app
      debug:
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Check for dependency update
        id: update-deps
        uses: ./.github/actions/js-dependency-update
        with:
          base-branch: ${{ inputs.base-branch }}
          head-branch: ${{ inputs.head-branch }}
          working-directory: ${{ inputs.working-directory }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          debug: ${{ inputs.debug }}

      - name: Print custom action output
        run: |
          echo "Updates available: ${{ steps.update-deps.outputs.updates-available }}"
