name: 17-3 - Custom Actions Docker

on:
  workflow_dispatch:
    inputs:
      url:
        description: URL to ping
        type: choice
        options:
          - "https://www.github.com"
          - "https://www.website-that-fails-foobarbaz.com"
          - "website-that-fails"
      max_attempts:
        description: Number of attempts before failure
        default: "10"
        required: false
      delay:
        description: Delay in seconds between attempts
        default: "5"
        required: false

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Ping URL
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ inputs.url }}
          max_attempts: ${{ inputs.max_attempts }}
          delay: ${{ inputs.delay }}
