name: 18-3 - Reusable Workflow

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/18-1-reusable-workflow.yaml
    with:
      target-directory: dummy-dir

  e2e-tests:
    uses: rslnv/gh-actions-beginner-expert-e2e/.github/workflows/e2e.yaml@main # tag, release or full sha can be used
    needs: deploy
    secrets:
      access-token: ${{ secrets.GH_TOKEN_E2E }}
